//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace entitydb
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        public int personid { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public Nullable<int> age { get; set; }
        public Nullable<int> phoneno { get; set; }
    }
}
