//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityCh1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Office
    {
        public int Office_id { get; set; }
        public string Office_Name { get; set; }
        public string Office_Address { get; set; }
        public Nullable<int> Phone { get; set; }
    }
}
